version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: owlPartners
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

  db-test:
    image: postgres
    environment:
      POSTGRES_DB: owlPartners-test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "8888:5432"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
